import { drizzle } from "drizzle-orm/node-postgres";
import {
  aiAssistant,
  aiPersonalityEnum,
  calendarDensityEnum,
  conversation,
  conversationRelations,
  energyLevelEnum,
  event,
  goal,
  goalRelations,
  goalStatusEnum,
  goalTypeEnum,
  message,
  messageRelations,
  milestone,
  milestoneRelations,
  project,
  projectRelations,
  review,
  reviewTypeEnum,
  roleEnum,
  subscriptionPlanEnum,
  subtask,
  subtaskRelations,
  tag,
  tagRelations,
  task,
  taskRelations,
  taskStatusEnum,
  taskTags,
  taskTagsRelations,
  userPurpose,
  userRelations,
  userSettings,
} from "./schema/app";
import { account, session, user, verification } from "./schema/auth";

export const schema = {
  account,
  session,
  user,
  verification,
  aiAssistant,
  aiPersonalityEnum,
  calendarDensityEnum,
  conversation,
  conversationRelations,
  energyLevelEnum,
  event,
  goal,
  goalRelations,
  goalStatusEnum,
  goalTypeEnum,
  message,
  messageRelations,
  milestone,
  milestoneRelations,
  project,
  projectRelations,
  review,
  reviewTypeEnum,
  roleEnum,
  subtask,
  subtaskRelations,
  subscriptionPlanEnum,
  tag,
  tagRelations,
  task,
  taskRelations,
  taskStatusEnum,
  taskTags,
  taskTagsRelations,
  userPurpose,
  userRelations,
  userSettings,
};

export const db = drizzle(process.env.DATABASE_URL || "", { schema });
